<?php

namespace Tests\Feature;

use App\Models\Label;
use App\Models\Task;
use App\Models\TaskStatus;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class LabelTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIndex(): void
    {
        $response = $this->get('/labels');
        $response->assertStatus(200);
    }

    public function testCreate(): void
    {
        $user = User::factory()->create();
        $data = Label::factory()->make()->toArray();
        $response = $this->actingAs($user)->post('/labels', $data);
        $response->assertStatus(302);
        $this->assertDatabaseHas('labels', $data);
        $response->assertSessionHas('labels');
    }

    public function testUpdate(): void
    {
        $user = User::factory()->create();
        $data = Label::factory()->make()->toArray();
        $this->actingAs($user)->post('/labels', $data);
        $dataNew = Label::factory()->make()->toArray();
        $label = Label::where('name', $data['name'])->first();
        $response = $this->actingAs($user)->patch("/labels/{$label->id}", $dataNew);
        $this->assertDatabaseHas('labels', $dataNew);
        $response->assertSessionHas('labels');
    }

    public function testDestroy(): void
    {
        //deleted
        $user = User::factory()->create();
        $data = Label::factory()->make()->toArray();
        $tasStatus = TaskStatus::factory()->create();
        $this->actingAs($user)->post('/labels', $data);
        $label = Label::where('name', $data['name'])->first();
        $response = $this->actingAs($user)->delete("/labels/{$label->id}");
        $this->assertDatabaseMissing('labels', [
            'name' => $label->name,
        ]);
        $response->assertSessionHas('labels');
        //undeleted
        $label2 = Label::factory()->create();
        $task = Task::factory()->for($user, 'creator')->create(['status_id' => $tasStatus->id]);
        $task->labeles()->attach([$label2->id]);
        $response = $this->actingAs($user)->delete("/labels/{$label2->id}");
        $response->assertSessionHas('alert');
        $this->assertDatabaseHas('labels', ['name' => $label2->name]);
    }
}
