<?php

namespace Tests\Feature;

use App\Models\Label;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class LabelTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIndex(): void
    {
        $response = $this->get('/labels');
        $response->assertStatus(200);
    }

    public function testCreate(): void
    {
        $user = User::factory()->create();
        $data = Label::factory()->make()->toArray();
        $response = $this->actingAs($user)->post('/labels', $data);
        $response->assertStatus(302);
        $this->assertDatabaseHas('labels', $data);
        $response->assertSessionHas('labels');
    }

    public function testUpdate(): void
    {
        $user = User::factory()->create();
        $data = Label::factory()->make()->toArray();
        $this->actingAs($user)->post('/labels', $data);
        $dataNew = Label::factory()->make()->toArray();
        $label = Label::where('name', $data['name'])->first();
        $response = $this->actingAs($user)->patch("/labels/{$label->id}", $dataNew);
        $this->assertDatabaseHas('labels', $dataNew);
        $response->assertSessionHas('labels');
    }

    public function testDestroy(): void
    {
        $user = User::factory()->create();
        $data = Label::factory()->make()->toArray();
        $this->actingAs($user)->post('/labels', $data);
        $label = Label::where('name', $data['name'])->first();
        $response = $this->actingAs($user)->delete("/labels/{$label->id}");
        $response->assertSessionHas('labels');
    }
}
