<?php

namespace Tests\Feature;

use App\Models\Label;
use App\Models\Task;
use App\Models\TaskStatus;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Sequence;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class TaskTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIndex(): void
    {
        $response = $this->get('/tasks');
        $response->assertStatus(200);
    }

    public function testCreate(): void
    {
        $user = User::factory()->create();
        $status = TaskStatus::factory()->create(['id' => 2]);
        $data1 = Task::factory()->for($user, 'creator')->for($status, 'status')
            ->state(new Sequence(
                ['assigned_to_id' => null],
            ))->make()->attributesToArray();
        $response = $this->actingAs($user)->post('/tasks', $data1);
        $response->assertStatus(302);
        $this->assertDatabaseHas('tasks', $data1);
        $response->assertSessionHas('task');

        $data2 = Task::factory()->for($user, 'creator')->for($status, 'status')
            ->state(new Sequence(
                ['assigned_to_id' => $user->id],
            ))->make()->attributesToArray();
        $response = $this->actingAs($user)->post('/tasks', $data2);
        $response->assertStatus(302);
        $this->assertDatabaseHas('tasks', $data2);
        $response->assertSessionHas('task');
    }

    public function testUpdate(): void
    {
        $user = User::factory()->create();
        $status = TaskStatus::factory()->create(['id' => 2]);
        $dataOld = Task::factory()->for($user, 'creator')->for($status, 'status')
            ->make()->attributesToArray();
        $response = $this->actingAs($user)->post('/tasks', $dataOld);
        $dataNew = Task::factory()->for($user, 'creator')->for($status, 'status')
            ->make()->attributesToArray();
        $task = Task::where('name', $dataOld['name'])->first();
        $this->actingAs($user)->patch("/tasks/{$task->id}", $dataNew);
        $this->assertDatabaseHas('tasks', $dataNew);
        $response->assertSessionHas('task');
    }

    public function testDestroy(): void
    {
        $user = User::factory()->create();
        $status = TaskStatus::factory()->create(['id' => 2]);
        $data = Task::factory()->for($user, 'creator')->for($status, 'status')
            ->make()->attributesToArray();
        $response = $this->actingAs($user)->post('/tasks', $data);
        $task = Task::where('name', $data['name'])->first();
        $this->actingAs($user)->delete("/tasks/{$task->id}");
        $response->assertSessionHas('task');
        $this->assertDatabaseMissing('tasks', [
            'name' => $task->name,
            'description' => $task->description,
        ]);
    }
}
