<?php

namespace Tests\Feature;

use App\Models\Task;
use App\Models\TaskStatus;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class TaskStatusTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIndex(): void
    {
        $response = $this->get('/task_statuses');
        $response->assertStatus(200);
    }

    public function testCreate(): void
    {
        $user = User::factory()->create();
     //$data = TaskStatus::factory()->make()->only('name');
        $data = ['name' => 'normal'];
        $response = $this->actingAs($user)->post('/task_statuses', $data);
        $response->assertStatus(302);
        $this->assertDatabaseHas('task_statuses', $data);
        $response->assertSessionHas('status');
    }

    public function testUpdate(): void
    {
        $user = User::factory()->create();
        $data = ['name' => 'normal'];
        $this->actingAs($user)->post('/task_statuses', $data);
        $this->assertDatabaseHas('task_statuses', $data);
        $newData = ['name'=>'good'];
        $taskStatus = TaskStatus::where('name', 'normal')->first()->toArray();
        $id = $taskStatus['id'];
        $response = $this->actingAs($user)->patch("/task_statuses/{$id}", $newData);
        $newTaskStatus = TaskStatus::find($id)->toArray();
        $this->assertEquals('good', $newTaskStatus['name']);
        $response->assertSessionHas('status');

    }

    public function testDestroy(): void
    {
        //deleted
        $user = User::factory()->create();
        $data = ['name' => 'normal'];
        $this->actingAs($user)->post('/task_statuses', $data);
        $taskStatus1 = TaskStatus::where('name', 'normal')->first();
        $response = $this->actingAs($user)->delete("/task_statuses/{$taskStatus1->id}");
        $this->assertDatabaseMissing('tasks', [
            'name'=>$taskStatus1->name,
        ]);
        $response->assertSessionHas('status');

        //undeleted
        $this->actingAs($user)->post('/task_statuses', $data);
        $taskStatus2 = TaskStatus::where('name', 'normal')->first();
        $task = Task::factory()->for($user, 'creator')->create(['status_id' => $taskStatus2->id]);
        $response = $this->actingAs($user)->delete("/task_statuses/{$taskStatus2->id}");
        $this->assertDatabaseHas('task_statuses', $data);
        $response->assertSessionHas('alert');
    }
}
